server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/end_to_end_project_db
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: muhammad4ammar23@gmail.com
    password: hslb ykxi vsex nise
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
